FROM node:16.16.0-alpine AS INSTALLER

WORKDIR /usr/src/app
COPY package.json yarn.lock ./

RUN yarn global add @nestjs/cli

COPY . .
RUN yarn --prod

RUN yarn build

FROM node:16.16.0-alpine

WORKDIR /usr/src/app

COPY --from=INSTALLER /usr/src/app .

ENV LAUNCH_ENV docker-compose
ARG DB_HOST 
ARG DB_PORT 
ARG DB_USERNAME 
ARG DB_PASSWORD 
ARG DB_DATABASE 
ARG CONTAINER_PORT 
ARG JWT_ACCESSTOKEN_SECRET
ARG JWT_REFRESHTOKEN_SECRET
ARG AWS_S3_BUCKET
ARG AWS_ACCESS_KEY
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION
ARG AWS_S3_BUCKET_URL

CMD ["node", "dist/main.js"]
EXPOSE ${CONTAINER_PORT}