export enum Category {
  SPORT = 'SPORT',
  CAR = 'CAR',
  FASHION = 'FASHION',
  HOME_APPLICES = 'HOME_APPLICES',
  FURNITURE = 'FURNITURE',
  OFFICE = 'OFFICE',
  DRINK = 'DRINK',
  HOME = 'HOME',
  ETC = 'ETC',
}
